server {
    listen 80;
    server_name localhost;

    # 根目录设置
    root /usr/share/nginx/html;
    index index.html;

    # 访问 /myEcharts 时指向对应的目录
    location /myEcharts {
        # 确保访问 /myEcharts 时自动索引到 index.html
        try_files $uri $uri/ /myEcharts/index.html;
    }
}